//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOKTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOKTER()
        {
            this.PEMERIKSAANs = new HashSet<PEMERIKSAAN>();
        }
    
        public int ID_DOKTER { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_SPESIALISASI { get; set; }
        public string NAMA { get; set; }
        public string PENDIDIKAN { get; set; }
        public string JENIS_KELAMIN { get; set; }
    
        public virtual SPESIALISASI SPESIALISASI { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEMERIKSAAN> PEMERIKSAANs { get; set; }
    }
}
