//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JADWAL
    {
        public int ID_JADWAL { get; set; }
        public int ID_PEMERIKSAAN { get; set; }
        public Nullable<System.DateTime> MULAI { get; set; }
        public Nullable<System.DateTime> SELESAI { get; set; }
        public string KEPERLUAN { get; set; }
        public string HASIL_PEMERIKSAAN { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual PEMERIKSAAN PEMERIKSAAN { get; set; }
    }
}
