//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASUS_STAT
    {
        public int ID_KASUS_STAT { get; set; }
        public int ID_KASUS { get; set; }
        public string STATUS_KASUS { get; set; }
        public System.DateTime TGL { get; set; }
    
        public virtual KASU KASU { get; set; }
    }
}
