//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PASIEN()
        {
            this.T_KASUS = new HashSet<T_KASUS>();
        }
    
        public int ID_PASIEN { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string NAMA { get; set; }
        public System.DateTime TGL_LAHIR { get; set; }
        public string ALAMAT { get; set; }
        public string JENIS_KELAMIN { get; set; }
        public string TELP { get; set; }
        public string TEMPAT_LAHIR { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_KASUS> T_KASUS { get; set; }
    }
}
