//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEMERIKSAAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEMERIKSAAN()
        {
            this.ORDER_MEDIS = new HashSet<ORDER_MEDIS>();
        }
    
        public int ID_PEMERIKSAAN { get; set; }
        public Nullable<int> ID_DOKTER { get; set; }
        public Nullable<int> ID_REKAM_MEDIS { get; set; }
        public System.DateTime TGL { get; set; }
        public string RUANGAN { get; set; }
    
        public virtual DOKTER DOKTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_MEDIS> ORDER_MEDIS { get; set; }
        public virtual REKAM_MEDIS REKAM_MEDIS { get; set; }
    }
}
