//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTER_KASUS
    {
        public string REG_NO { get; set; }
        public string NAMA { get; set; }
        public string KELUHAN { get; set; }
        public Nullable<int> TINGGI_BADAN { get; set; }
        public Nullable<int> BERAT_BADAN { get; set; }
        public Nullable<int> TENSI_DARAH { get; set; }
        public Nullable<int> ID_KLINIK { get; set; }
    
        public virtual KLINIK KLINIK { get; set; }
        public virtual T_KASUS T_KASUS { get; set; }
    }
}
