//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class REKAM_MEDIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REKAM_MEDIS()
        {
            this.PEMERIKSAANs = new HashSet<PEMERIKSAAN>();
        }
    
        public int ID_REKAM_MEDIS { get; set; }
        public string GEJALA { get; set; }
        public string TINDAKAN { get; set; }
        public string VONIS { get; set; }
        public string DIAGNOSA { get; set; }
        public string HASIL_TEST_LAB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEMERIKSAAN> PEMERIKSAANs { get; set; }
    }
}
