//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KASUS
    {
        public string REG_NO { get; set; }
        public int ID_KASUS { get; set; }
        public int ID_PASIEN { get; set; }
        public string VRF_DATA_PASIEN { get; set; }
        public string VRF_KELUHAN_PASIEN { get; set; }
        public string VRF_HISTORICAL_DATA { get; set; }
        public Nullable<System.DateTime> TGL_MASUK { get; set; }
    
        public virtual KASU KASU { get; set; }
        public virtual PASIEN PASIEN { get; set; }
        public virtual REGISTER_KASUS REGISTER_KASUS { get; set; }
    }
}
