//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ALOKASI_DOKTER
    {
        public int ID_DOKTER { get; set; }
        public string NAMA_DOKTER { get; set; }
        public string JENIS_SPESIALISASI { get; set; }
        public Nullable<int> JUMLAH_PASIEN { get; set; }
    }
}
