//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Sistem_Informasi_RS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ORDER_MEDIS
    {
        public int ID_ORDER { get; set; }
        public Nullable<int> ID_PEMERIKSAAN { get; set; }
        public Nullable<int> ID_PASIEN { get; set; }
        public Nullable<int> JENIS_ORDER_MEDIS { get; set; }
        public string JENIS { get; set; }
        public Nullable<int> ID { get; set; }
        public string NAMA { get; set; }
        public Nullable<int> JUMLAH { get; set; }
    }
}
